### PR TITLE
Added yarn

### PR DESCRIPTION
**Pull request by munir131**
Many developers are now switched to yarn for manage packages. Let's add yarn in this library.

### CODE REVIEW

**Comment by munir131** [comment]
Related post: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all

**Comment by ghaiklor** [comment]
LGTM @drudge

**Comment by drudge** [comment]
LGTM too!

**Comment by ghaiklor** [comment]
@drudge @munir131 published as 1.3.0

**Pull request merged**
